project:
  type: website
  output-dir: docs

website:
  title: "Nibia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects Overview
      - text: Air Data Processing and Visualizations 
        menu:
          - text: Laboratory Gas Data Processing
            href: LabGas.qmd
          - text: Field Gas Data Processing
            href: FieldGas.qmd
      - text: Data Science Projects
        menu:
          - text: Difference in Difference
            href: DiD_ColombiaVenezuela.qmd
          - text: LDA thematic analysis
            href: LDA_thematic_analysis/Report.qmd
          - text: Clustering
            href: Clustering.qmd
      - text: STAT Content Summary
        menu:
          - text: Intro to GWAS
            href: Content_Summary.qmd
          - text: PCA for GWAS 
            href: ContentSummary2forreal.qmd
                
    right:
      - icon: envelope
        href: "mailto:nibiab.work@gmail.com"
      - text: LinkedIn
        icon: linkedin
        href: "https://www.linkedin.com/in/nibia-becerra-santillan/"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



